name: Deploy GitHub Pages for any branch

on:
  push:
    branches:
      - '**' # Trigger on any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build and Deploy
      run: |
        mkdir -p public
        echo "<h1>GitHub Pages Deployed</h1>" > public/index.html
        echo "Deployed from branch: $GITHUB_REF_NAME" >> public/index.html

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v1

  pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2